steps:
  - name: 'golang:1.14.7'
    id: Test
    args:
      - 'go'
      - 'test'
      - './...'
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bajidspotifyserver:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bajidspotifyserver:$SHORT_SHA'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'bajidspotifyserver'
      - '--image'
      - 'gcr.io/$PROJECT_ID/bajidspotifyserver:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--max-instances'
      - '2'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=${_PROJECT_ID},SPOTIFY_CLIENT_ID=${_SPOTIFY_CLIENT_ID},SPOTIFY_REDIRECT_URI=${_SPOTIFY_REDIRECT_URI},SPOTIFY_CLIENT_SECRET=${_SPOTIFY_CLIENT_SECRET}'
