steps:
  - name: 'golang:1.14.7'
    id: Test
    args:
      - 'go'
      - 'test'
      - './...'
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bajidspotifyserver:$SHORT_SHA'
      - '.'
